ciphertext = "YYIWJJMXZRXMTEWEXIIGFCPIISCTQRXSFEHEXMMZNUPCFTXIILTSSSCGTIXIEYEZJRGSRDSRFEHMSKIVJJXMSXYRIVVPDZRKQFKMHESXNTIXMRXXMVWSQUMIWJEVJESXRFXMARXIIKSVJKVIFKNYXKSVJMIRRRMRQPFCYYIMWIEXNFREQRWWJJWQJEXSKKLIIRRKJIWSKSEXYCIESUFCYYIMWJIPKZRXJIIWYIEXMVVXMVCHNJGSAVVEXFYRIIIEXFRXTIYRFNECGPVIFCMDNEKXMRXAMRXMYDEOJJWISJIJTIXLJDXSIFHIUVRHXFRAMRXMYNMPQDEOJJIRXVJSWFXLJIWXTUSESUXLFKEPQFJXMVSXMVVWHRRRTKMGJKLMXKSSJMIRFHYMYVFVFMIWTCHMJIQEDGVIKVVXTIYRWRXLJIXLFELIWFMGFCPCGLXTTZRXQVWWQPHMJKVCNEKXTJXIRKLITEGSRZRKYZHIFCPFDYMQXVPJYYYWBVGSZCHMRRKMSVAMYYSYYTSRYIEHNTXMTEEGNIGYRJXESTIMSNLMHYERFIQCFCPSKNLSXVQIRSIVXRVIGIEZJWPIJJEXYFTWUVIHGVJSWVXLJVRIRPQEPVWERFZINWXLJJSPIZIVXIIEQCCEWVFVFMIXMV"
Y1 = ""
Y2 = ""
Y3 = ""
Y4 = ""
position = 0
for char in ciphertext:
    if position % 4 == 0:
        Y1 = Y1 + char
    elif position % 4 == 1:
        Y2 = Y2 + char
    elif position % 4 == 2:
        Y3 = Y3 + char
    else:
        Y4 = Y4 + char
    position = position + 1

print "Y1:" + Y1
print "Y2:" + Y2
print "Y3:" + Y3
print "Y4:" + Y4
